name: Deploy Insurance App - Agent

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Generate .env file
        run: |
          cat <<EOF > .env
          NEXT_PUBLIC_TOKEN=${{ secrets.NEXT_PUBLIC_TOKEN }}
          BASE_URL=${{ secrets.BASE_URL }}
          GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}
          EOF

      - name: Clean and install prod dependencies
        run: |
          rm -f package-lock.json
          npm install

      - name: Build app
        run: |
          npm run build
          npm prune --omit=dev

      - name: Show build files
        run: ls -lah 

      - name: Archive build
        run: tar -czf nextjs-build.tar.gz .next node_modules public package.json package-lock.json next.config.ts tsconfig.json .env auth.db

      - name: Upload production bundle
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: nextjs-build.tar.gz


  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build

      - name: Clean previous deploy
        run: |
          rm -rf .next node_modules public package.json package-lock.json next.config.ts tsconfig.json .env

      - name: Extract build
        run: |
          tar -xzf nextjs-build.tar.gz
          rm nextjs-build.tar.gz

      - name: Show downloaded files
        run: ls -lah

      - name: Use Node.js 22
        run: |
          source ~/.nvm/nvm.sh
          nvm use 22

      - name: Restart app with PM2
        run: |
          pm2 delete insurance-agent || true
          PORT=4000 pm2 start "npx next start" --name "insurance-agent"
          pm2 save
